### model
model_name_or_path: XXX
trust_remote_code: true
flash_attn: fa2 

### method
stage: sft
do_train: true
finetuning_type: full
save_only_model: true
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: cog_safr_data
template: qwen3
cutoff_len: 8192
max_samples: 25000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: COG/output_model/Qwen3-SafR/

logging_steps: 1
save_steps: 200
plot_loss: true
overwrite_output_dir: true
report_to: 
use_swanlab: true
swanlab_run_name: 

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 0.000002
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
